<?xml version="1.0" encoding="utf-8"?><Database Name="SoLieuTongHop" Class="linqCSKHMucDoanhThuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=SoLieuTongHop;User ID=BaoCaoSL" SettingsObjectName="daoSLTH.Properties.Settings" SettingsPropertyName="SoLieuTongHopConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblcskhMucDoanhThu_DanhSach" Method="sp_tblcskhMucDoanhThu_DanhSach">
    <ElementType Name="sp_tblcskhMucDoanhThu_DanhSachResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MucDuoi" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="MucTren" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblcskhMucDoanhThu_ThemSua" Method="sp_tblcskhMucDoanhThu_ThemSua">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ma" Parameter="ma" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Ten" Parameter="ten" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="MucDuoi" Parameter="mucDuoi" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="MucTren" Parameter="mucTren" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="GhiChu" Parameter="ghiChu" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblcskhMucDoanhThu_KiemTra" Method="sp_tblcskhMucDoanhThu_KiemTra">
    <Parameter Name="MucDuoi" Parameter="mucDuoi" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="MucTren" Parameter="mucTren" Type="System.Decimal" DbType="Decimal(10,2)" />
    <ElementType Name="sp_tblcskhMucDoanhThu_KiemTraResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MucDuoi" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="MucTren" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>