#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daoSLBC.Database.HeThong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SoLieuBaoCao")]
	public partial class linqDangNhapDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqDangNhapDataContext() : 
				base(global::daoSLBC.Properties.Settings.Default.SoLieuBaoCaoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqDangNhapDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDangNhapDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDangNhapDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDangNhapDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_KiemTraDangNhap")]
		public ISingleResult<sp_KiemTraDangNhapResult> sp_KiemTraDangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNSD", DbType="NVarChar(20)")] string maNSD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNSD, maDonVi);
			return ((ISingleResult<sp_KiemTraDangNhapResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_KiemTraDangNhapResult
	{
		
		private string _KetQuaKiemTra;
		
		private string _TenDonVi;
		
		private string _TenTatDonVi;
		
		private string _TenRutGonDonVi;
		
		private string _MaSTK1;
		
		public sp_KiemTraDangNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQuaKiemTra", DbType="NVarChar(70)")]
		public string KetQuaKiemTra
		{
			get
			{
				return this._KetQuaKiemTra;
			}
			set
			{
				if ((this._KetQuaKiemTra != value))
				{
					this._KetQuaKiemTra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonVi", DbType="NVarChar(80)")]
		public string TenDonVi
		{
			get
			{
				return this._TenDonVi;
			}
			set
			{
				if ((this._TenDonVi != value))
				{
					this._TenDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTatDonVi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TenTatDonVi
		{
			get
			{
				return this._TenTatDonVi;
			}
			set
			{
				if ((this._TenTatDonVi != value))
				{
					this._TenTatDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenRutGonDonVi", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TenRutGonDonVi
		{
			get
			{
				return this._TenRutGonDonVi;
			}
			set
			{
				if ((this._TenRutGonDonVi != value))
				{
					this._TenRutGonDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSTK1", DbType="NVarChar(10)")]
		public string MaSTK1
		{
			get
			{
				return this._MaSTK1;
			}
			set
			{
				if ((this._MaSTK1 != value))
				{
					this._MaSTK1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
