#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daoSLBC.Database.HeThong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SoLieuBaoCao")]
	public partial class linqDangNhapDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqDangNhapDataContext() : 
				base(global::daoSLBC.Properties.Settings.Default.SoLieuBaoCaoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqDangNhapDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDangNhapDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDangNhapDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDangNhapDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_NguoiSuDung_DanhSach")]
		public ISingleResult<sp_NguoiSuDung_DanhSachResult> sp_NguoiSuDung_DanhSach()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_NguoiSuDung_DanhSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_KiemTraDangNhap")]
		public ISingleResult<sp_KiemTraDangNhapResult> sp_KiemTraDangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNSD", DbType="NVarChar(20)")] string maNSD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNSD, maDonVi);
			return ((ISingleResult<sp_KiemTraDangNhapResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DonVi_DanhSach")]
		public ISingleResult<sp_DonVi_DanhSachResult> sp_DonVi_DanhSach()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_DonVi_DanhSachResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_NguoiSuDung_DanhSachResult
	{
		
		private string _MaNSD;
		
		private string _TenNguoiSuDung;
		
		private string _MaDonVi;
		
		private string _TenDonVi;
		
		public sp_NguoiSuDung_DanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSD", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaNSD
		{
			get
			{
				return this._MaNSD;
			}
			set
			{
				if ((this._MaNSD != value))
				{
					this._MaNSD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiSuDung", DbType="NVarChar(70)")]
		public string TenNguoiSuDung
		{
			get
			{
				return this._TenNguoiSuDung;
			}
			set
			{
				if ((this._TenNguoiSuDung != value))
				{
					this._TenNguoiSuDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="NVarChar(10)")]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					this._MaDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonVi", DbType="NVarChar(81)")]
		public string TenDonVi
		{
			get
			{
				return this._TenDonVi;
			}
			set
			{
				if ((this._TenDonVi != value))
				{
					this._TenDonVi = value;
				}
			}
		}
	}
	
	public partial class sp_KiemTraDangNhapResult
	{
		
		private string _TenNguoiSuDung;
		
		private string _Ma;
		
		private string _Ten;
		
		private System.Nullable<int> _Cap;
		
		private string _MaNSD;
		
		private string _MaSTK1;
		
		public sp_KiemTraDangNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiSuDung", DbType="NVarChar(50)")]
		public string TenNguoiSuDung
		{
			get
			{
				return this._TenNguoiSuDung;
			}
			set
			{
				if ((this._TenNguoiSuDung != value))
				{
					this._TenNguoiSuDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="NVarChar(255)")]
		public string Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this._Ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(255)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this._Ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap", DbType="Int")]
		public System.Nullable<int> Cap
		{
			get
			{
				return this._Cap;
			}
			set
			{
				if ((this._Cap != value))
				{
					this._Cap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSD", DbType="NVarChar(10)")]
		public string MaNSD
		{
			get
			{
				return this._MaNSD;
			}
			set
			{
				if ((this._MaNSD != value))
				{
					this._MaNSD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSTK1", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MaSTK1
		{
			get
			{
				return this._MaSTK1;
			}
			set
			{
				if ((this._MaSTK1 != value))
				{
					this._MaSTK1 = value;
				}
			}
		}
	}
	
	public partial class sp_DonVi_DanhSachResult
	{
		
		private int _ID;
		
		private string _Ma;
		
		private string _Ten;
		
		private System.Nullable<int> _Cap;
		
		private string _TenTat;
		
		private string _TenRutGon;
		
		private System.Nullable<decimal> _STTsx;
		
		private string _MaSTK1;
		
		private string _MaBuuChinh;
		
		private System.Nullable<decimal> _STTdt;
		
		private string _MaDonViBCOL;
		
		private string _TenDonViDTPC;
		
		private string _TenDonViDTPC2;
		
		private string _MaPaypost;
		
		public sp_DonVi_DanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="NVarChar(10)")]
		public string Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this._Ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(80)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this._Ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap", DbType="Int")]
		public System.Nullable<int> Cap
		{
			get
			{
				return this._Cap;
			}
			set
			{
				if ((this._Cap != value))
				{
					this._Cap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTat", DbType="NVarChar(20)")]
		public string TenTat
		{
			get
			{
				return this._TenTat;
			}
			set
			{
				if ((this._TenTat != value))
				{
					this._TenTat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenRutGon", DbType="NVarChar(40)")]
		public string TenRutGon
		{
			get
			{
				return this._TenRutGon;
			}
			set
			{
				if ((this._TenRutGon != value))
				{
					this._TenRutGon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTsx", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STTsx
		{
			get
			{
				return this._STTsx;
			}
			set
			{
				if ((this._STTsx != value))
				{
					this._STTsx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSTK1", DbType="NVarChar(10)")]
		public string MaSTK1
		{
			get
			{
				return this._MaSTK1;
			}
			set
			{
				if ((this._MaSTK1 != value))
				{
					this._MaSTK1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuuChinh", DbType="NVarChar(10)")]
		public string MaBuuChinh
		{
			get
			{
				return this._MaBuuChinh;
			}
			set
			{
				if ((this._MaBuuChinh != value))
				{
					this._MaBuuChinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTdt", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> STTdt
		{
			get
			{
				return this._STTdt;
			}
			set
			{
				if ((this._STTdt != value))
				{
					this._STTdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonViBCOL", DbType="NVarChar(10)")]
		public string MaDonViBCOL
		{
			get
			{
				return this._MaDonViBCOL;
			}
			set
			{
				if ((this._MaDonViBCOL != value))
				{
					this._MaDonViBCOL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonViDTPC", DbType="NVarChar(150)")]
		public string TenDonViDTPC
		{
			get
			{
				return this._TenDonViDTPC;
			}
			set
			{
				if ((this._TenDonViDTPC != value))
				{
					this._TenDonViDTPC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonViDTPC2", DbType="NVarChar(150)")]
		public string TenDonViDTPC2
		{
			get
			{
				return this._TenDonViDTPC2;
			}
			set
			{
				if ((this._TenDonViDTPC2 != value))
				{
					this._TenDonViDTPC2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPaypost", DbType="NVarChar(10)")]
		public string MaPaypost
		{
			get
			{
				return this._MaPaypost;
			}
			set
			{
				if ((this._MaPaypost != value))
				{
					this._MaPaypost = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
