<?xml version="1.0" encoding="utf-8"?><Database Name="SoLieuBaoCao" Class="linqChucNangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=SoLieuBaoCao;Persist Security Info=True;User ID=sa" SettingsObjectName="daoSLBC.Properties.Settings" SettingsPropertyName="SoLieuBaoCaoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblChucNang_DanhSach" Method="sp_tblChucNang_DanhSach">
    <Parameter Name="Nhom" Parameter="nhom" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblChucNang_DanhSachResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Muc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dcUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BieuTuong" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="MauChu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MauNen" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IDTren" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblChucNang_ThongTin" Method="sp_tblChucNang_ThongTin">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblChucNang_ThongTinResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Muc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dcUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BieuTuong" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="MauChu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MauNen" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IDTren" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblChucNang_DanhSach_TheoCapTren" Method="sp_tblChucNang_DanhSach_TheoCapTren">
    <Parameter Name="IDTren" Parameter="iDTren" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblChucNang_DanhSach_TheoCapTrenResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Muc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dcUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BieuTuong" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="MauChu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MauNen" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IDTren" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>