#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SoLieuBCOL")]
	public partial class linqB02KTNVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqB02KTNVDataContext() : 
				base(global::Test.Properties.Settings.Default.SoLieuBCOLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqB02KTNVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqB02KTNVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqB02KTNVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqB02KTNVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblBaoCaoB02KTNV_Them")]
		public int sp_tblBaoCaoB02KTNV_Them([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thang", DbType="SmallInt")] System.Nullable<short> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSo", DbType="NVarChar(10)")] string maSo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChiTieu", DbType="NVarChar(150)")] string chiTieu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonViTinh", DbType="NVarChar(30)")] string donViTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SanLuong", DbType="Decimal(20,0)")] System.Nullable<decimal> sanLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DoanhThuPS", DbType="Decimal(22,0)")] System.Nullable<decimal> doanhThuPS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DoanhThuLK", DbType="Decimal(25,0)")] System.Nullable<decimal> doanhThuLK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThueSuat", DbType="NVarChar(10)")] string thueSuat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThuePS", DbType="Decimal(20,0)")] System.Nullable<decimal> thuePS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThueLK", DbType="Decimal(20,0)")] System.Nullable<decimal> thueLK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SanLuongNghiepVuDi", DbType="Decimal(20,0)")] System.Nullable<decimal> sanLuongNghiepVuDi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SanLuongDen", DbType="Decimal(20,0)")] System.Nullable<decimal> sanLuongDen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam, maDonVi, maSo, chiTieu, donViTinh, sanLuong, doanhThuPS, doanhThuLK, thueSuat, thuePS, thueLK, sanLuongNghiepVuDi, sanLuongDen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblBaoCaoB02KTNV_ThongTin")]
		public ISingleResult<sp_tblBaoCaoB02KTNV_ThongTinResult> sp_tblBaoCaoB02KTNV_ThongTin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thang", DbType="SmallInt")] System.Nullable<short> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSo", DbType="NVarChar(10)")] string maSo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam, maDonVi, maSo);
			return ((ISingleResult<sp_tblBaoCaoB02KTNV_ThongTinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblBaoCaoB02KTNV_Xoa")]
		public int sp_tblBaoCaoB02KTNV_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thang", DbType="SmallInt")] System.Nullable<short> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam, maDonVi);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_tblBaoCaoB02KTNV_ThongTinResult
	{
		
		private System.Nullable<short> _Thang;
		
		private System.Nullable<int> _Nam;
		
		private string _MaDonVi;
		
		private string _ChiTieu;
		
		private string _DonViTinh;
		
		private string _MaSo;
		
		private System.Nullable<decimal> _SanLuong;
		
		private System.Nullable<decimal> _DoanhThuPS;
		
		private System.Nullable<decimal> _DoanhThuLK;
		
		private string _ThueSuat;
		
		private System.Nullable<decimal> _ThuePS;
		
		private System.Nullable<decimal> _ThueLK;
		
		private System.Nullable<decimal> _SanLuongNghiepVuDi;
		
		private System.Nullable<decimal> _SanLuongDen;
		
		private System.Nullable<System.DateTime> _NgayHeThong;
		
		public sp_tblBaoCaoB02KTNV_ThongTinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="SmallInt")]
		public System.Nullable<short> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this._Thang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="NVarChar(10)")]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					this._MaDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiTieu", DbType="NVarChar(150)")]
		public string ChiTieu
		{
			get
			{
				return this._ChiTieu;
			}
			set
			{
				if ((this._ChiTieu != value))
				{
					this._ChiTieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(20)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this._DonViTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSo", DbType="NVarChar(10)")]
		public string MaSo
		{
			get
			{
				return this._MaSo;
			}
			set
			{
				if ((this._MaSo != value))
				{
					this._MaSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanLuong", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> SanLuong
		{
			get
			{
				return this._SanLuong;
			}
			set
			{
				if ((this._SanLuong != value))
				{
					this._SanLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoanhThuPS", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DoanhThuPS
		{
			get
			{
				return this._DoanhThuPS;
			}
			set
			{
				if ((this._DoanhThuPS != value))
				{
					this._DoanhThuPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoanhThuLK", DbType="Decimal(25,0)")]
		public System.Nullable<decimal> DoanhThuLK
		{
			get
			{
				return this._DoanhThuLK;
			}
			set
			{
				if ((this._DoanhThuLK != value))
				{
					this._DoanhThuLK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThueSuat", DbType="NVarChar(10)")]
		public string ThueSuat
		{
			get
			{
				return this._ThueSuat;
			}
			set
			{
				if ((this._ThueSuat != value))
				{
					this._ThueSuat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuePS", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ThuePS
		{
			get
			{
				return this._ThuePS;
			}
			set
			{
				if ((this._ThuePS != value))
				{
					this._ThuePS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThueLK", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> ThueLK
		{
			get
			{
				return this._ThueLK;
			}
			set
			{
				if ((this._ThueLK != value))
				{
					this._ThueLK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanLuongNghiepVuDi", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> SanLuongNghiepVuDi
		{
			get
			{
				return this._SanLuongNghiepVuDi;
			}
			set
			{
				if ((this._SanLuongNghiepVuDi != value))
				{
					this._SanLuongNghiepVuDi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanLuongDen", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> SanLuongDen
		{
			get
			{
				return this._SanLuongDen;
			}
			set
			{
				if ((this._SanLuongDen != value))
				{
					this._SanLuongDen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHeThong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHeThong
		{
			get
			{
				return this._NgayHeThong;
			}
			set
			{
				if ((this._NgayHeThong != value))
				{
					this._NgayHeThong = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
