<?xml version="1.0" encoding="utf-8"?><Database Name="SoLieuPhatHanh" Class="linqLayDuLieuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=SoLieuPhatHanh;User ID=sa" SettingsObjectName="daoSLPH.Properties.Settings" SettingsPropertyName="SoLieuPhatHanhConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblLanLayDuLieu_Them" Method="sp_tblLanLayDuLieu_Them">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="MAC" Parameter="mAC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DiaChiIP" Parameter="diaChiIP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DichVu" Parameter="dichVu" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="SoLuong" Parameter="soLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="TongTien" Parameter="tongTien" Type="System.Decimal" DbType="Decimal(22,0)" />
    <Parameter Name="ThoiGianBatDau" Parameter="thoiGianBatDau" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ThoiGianKetThuc" Parameter="thoiGianKetThuc" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblLanLayDuLieu_ThongTin" Method="sp_tblLanLayDuLieu_ThongTin">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_tblLanLayDuLieu_ThongTinResult">
      <Column Name="MaBuuCuc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MAC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiIP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DichVu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="ThoiGianBatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayHeThong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>