<?xml version="1.0" encoding="utf-8"?><Database Name="SoLieuTongHop" Class="linqKetSatDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=SoLieuTongHop;Persist Security Info=True;User ID=sa" SettingsObjectName="daoSLTH.Properties.Settings" SettingsPropertyName="SoLieuTongHopConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblKetSat_TheoDoi_BuuCuc" Method="sp_tblKetSat_TheoDoi_BuuCuc">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_tblKetSat_TheoDoi_BuuCucResult">
      <Column Name="DonVi" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="MaBuuCuc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TenBuuCuc" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="TenGop" Type="System.String" DbType="NVarChar(103)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DuDau" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NhanTiepQuy" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PSCo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PSCoNhap" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PSNo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PSNoNhap" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NopTienMat" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NopTienChuyenKhoan" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DuCuoi" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NgayHeThong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKetSatCoNo_TongHop" Method="sp_tblKetSatCoNo_TongHop">
    <Parameter Name="Ngay" Parameter="ngay" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKetSat_TongHop" Method="sp_tblKetSat_TongHop">
    <Parameter Name="Ngay" Parameter="ngay" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKetSat_ThongTin" Method="sp_tblKetSat_ThongTin">
    <Parameter Name="MaDoiSoat" Parameter="maDoiSoat" Type="System.String" DbType="NVarChar(16)" />
    <ElementType Name="sp_tblKetSat_ThongTinResult">
      <Column Name="MaDoiSoat" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaBuuCuc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DuDau" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NhanTiepQuy" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PSCo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PSCoNhap" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PSNo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PSNoNhap" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NopTienMat" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NopTienChuyenKhoan" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DuCuoi" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NgayHeThong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>