<?xml version="1.0" encoding="utf-8"?><Database Name="SoLieuBaoCao" Class="linqDuLieuBaocaoTapHopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=SoLieuBaoCao;Persist Security Info=True;User ID=sa" SettingsObjectName="daoSLBC.Properties.Settings" SettingsPropertyName="SoLieuBaoCaoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblDuLieuBaoCaoNhanhTapHop_ChiTietDonVi" Method="sp_tblDuLieuBaoCaoNhanhTapHop_ChiTietDonVi">
    <Parameter Name="MaBieuBaoCao" Parameter="maBieuBaoCao" Type="System.String" DbType="NVarChar(16)" />
    <Parameter Name="LoaiDuLieu" Parameter="loaiDuLieu" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblDuLieuBaoCaoNhanhTapHop_TapHop" Method="sp_tblDuLieuBaoCaoNhanhTapHop_TapHop">
    <Parameter Name="MaBieuBaoCao" Parameter="maBieuBaoCao" Type="System.String" DbType="NVarChar(16)" />
    <Parameter Name="LaBCN" Parameter="laBCN" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblDuLieuBaoCaoNhanhTapHop_DanhSachBaoCao" Method="sp_tblDuLieuBaoCaoNhanhTapHop_DanhSachBaoCao">
    <Parameter Name="MaBieuBaoCao" Parameter="maBieuBaoCao" Type="System.String" DbType="NVarChar(16)" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaDonVi" Parameter="maDonVi" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_tblDuLieuBaoCaoNhanhTapHop_DanhSachBaoCaoResult">
      <Column Name="MaBieuBaoCao" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="IDChiTieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThuTu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TenChiTieu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MaSoChiTieu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="KeHoachGiao" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="SoLieuSTK1" Type="System.Decimal" DbType="Decimal(25,3)" CanBeNull="true" />
      <Column Name="SoLieuNhap" Type="System.Decimal" DbType="Decimal(25,3)" CanBeNull="true" />
      <Column Name="SoLieuPhanBo" Type="System.Decimal" DbType="Decimal(25,3)" CanBeNull="true" />
      <Column Name="CongSoLieuBCN" Type="System.Decimal" DbType="Decimal(26,3)" CanBeNull="true" />
      <Column Name="SoLieuThucHien" Type="System.Decimal" DbType="Decimal(25,3)" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="InDam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InNghieng" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NhapTay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblDuLieuBaoCaoNhanhTapHop_KhoiTao" Method="sp_tblDuLieuBaoCaoNhanhTapHop_KhoiTao">
    <Parameter Name="MaBieuBaoCao" Parameter="maBieuBaoCao" Type="System.String" DbType="NVarChar(16)" />
    <Parameter Name="IDMauBieu" Parameter="iDMauBieu" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblDuLieuBaoCaoNhanhTapHop_CapNhatBaoCao" Method="sp_tblDuLieuBaoCaoNhanhTapHop_CapNhatBaoCao">
    <Parameter Name="MaBieuBaoCao" Parameter="maBieuBaoCao" Type="System.String" DbType="NVarChar(16)" />
    <Parameter Name="IDChiTieu" Parameter="iDChiTieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="SoLieuNhap" Parameter="soLieuNhap" Type="System.Decimal" DbType="Decimal(25,3)" />
    <Parameter Name="NguoiNhapBCN" Parameter="nguoiNhapBCN" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblDuLieuBaoCaoNhanhTapHop_CapNhatThucHien" Method="sp_tblDuLieuBaoCaoNhanhTapHop_CapNhatThucHien">
    <Parameter Name="MaBieuBaoCao" Parameter="maBieuBaoCao" Type="System.String" DbType="NVarChar(16)" />
    <Parameter Name="IDChiTieu" Parameter="iDChiTieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="SoLieuThucHien" Parameter="soLieuThucHien" Type="System.Decimal" DbType="Decimal(25,3)" />
    <Parameter Name="NguoiNhapTH" Parameter="nguoiNhapTH" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>