#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daoSLBC.Database.DuLieuBaoCao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SoLieuBaoCao")]
	public partial class linqDuLieuChiTietSTK1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqDuLieuChiTietSTK1DataContext() : 
				base(global::daoSLBC.Properties.Settings.Default.SoLieuBaoCaoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqDuLieuChiTietSTK1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDuLieuChiTietSTK1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDuLieuChiTietSTK1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDuLieuChiTietSTK1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblDuLieuBaoCaoNhanh_TinhDanSuat_Nhap")]
		public ISingleResult<clsTinhDanSuat> sp_tblDuLieuBaoCaoNhanh_TinhDanSuat_Nhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDMauBieu", DbType="Int")] System.Nullable<int> iDMauBieu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBieuBaoCao", DbType="NVarChar(16)")] string maBieuBaoCao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDChiTieuNhap", DbType="Int")] System.Nullable<int> iDChiTieuNhap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChenhLech", DbType="Decimal(25,3)")] System.Nullable<decimal> chenhLech)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDMauBieu, maBieuBaoCao, iDChiTieuNhap, chenhLech);
			return ((ISingleResult<clsTinhDanSuat>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblDuLieuBaoCaoNhanh_ChiTiet_STK1")]
		public ISingleResult<clsChiTietDichVu> sp_tblDuLieuBaoCaoNhanh_ChiTiet_STK1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBieuBaoCao", DbType="NVarChar(16)")] string maBieuBaoCao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDChiTieu", DbType="Int")] System.Nullable<int> iDChiTieu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBieuBaoCao, iDChiTieu);
			return ((ISingleResult<clsChiTietDichVu>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblDuLieuBaoCaoNhanh_ChiTiet_STK1_ThoiGian")]
		public ISingleResult<clsChiTietNgay> sp_tblDuLieuBaoCaoNhanh_ChiTiet_STK1_ThoiGian([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBieuBaoCao", DbType="NVarChar(16)")] string maBieuBaoCao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDChiTieu", DbType="Int")] System.Nullable<int> iDChiTieu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBieuBaoCao, iDChiTieu);
			return ((ISingleResult<clsChiTietNgay>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblDuLieuBaoCaoNhanh_ChiTiet_STK1_DonVi")]
		public ISingleResult<clsChiTietNgay> sp_tblDuLieuBaoCaoNhanh_ChiTiet_STK1_DonVi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBieuBaoCao", DbType="NVarChar(16)")] string maBieuBaoCao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDChiTieu", DbType="Int")] System.Nullable<int> iDChiTieu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBieuBaoCao, iDChiTieu);
			return ((ISingleResult<clsChiTietNgay>)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
