<?xml version="1.0" encoding="utf-8"?><Database Name="SoLieuBaoCao" Class="linqSoLieuSTK1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=SoLieuBaoCao;Persist Security Info=True;User ID=sa" SettingsObjectName="daoSLBC.Properties.Settings" SettingsPropertyName="SoLieuBaoCaoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblSoLieuSTK1Ngay_LayDuLieu" Method="sp_tblSoLieuSTK1Ngay_LayDuLieu">
    <Parameter Name="Thang" Parameter="thang" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblSoLieuSTK1Ngay_LayDuLieu_DonVi" Method="sp_tblSoLieuSTK1Ngay_LayDuLieu_DonVi">
    <Parameter Name="Thang" Parameter="thang" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaDonVi" Parameter="maDonVi" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
</Database>