#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daoTienThuCOD.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TienCOD")]
	public partial class linqBuuCucHuyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqBuuCucHuyDataContext() : 
				base(global::daoTienThuCOD.Properties.Settings.Default.TienCODConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqBuuCucHuyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqBuuCucHuyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqBuuCucHuyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqBuuCucHuyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblBuuCucHuy_DanhSach")]
		public ISingleResult<sp_tblBuuCucHuy_DanhSachResult> sp_tblBuuCucHuy_DanhSach([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="Date")] System.Nullable<System.DateTime> denNgay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc, tuNgay, denNgay);
			return ((ISingleResult<sp_tblBuuCucHuy_DanhSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblBuuCucHuy_ThongTin")]
		public ISingleResult<sp_tblBuuCucHuy_ThongTinResult> sp_tblBuuCucHuy_ThongTin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemCode", DbType="NVarChar(20)")] string itemCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc, itemCode);
			return ((ISingleResult<sp_tblBuuCucHuy_ThongTinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblBuuCucHuy_DanhSach_THop")]
		public ISingleResult<sp_tblBuuCucHuy_DanhSach_THopResult> sp_tblBuuCucHuy_DanhSach_THop([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="Date")] System.Nullable<System.DateTime> denNgay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc, tuNgay, denNgay);
			return ((ISingleResult<sp_tblBuuCucHuy_DanhSach_THopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblBuuCucHuy_Them")]
		public int sp_tblBuuCucHuy_Them(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay", DbType="Date")] System.Nullable<System.DateTime> ngay, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ca", DbType="SmallInt")] System.Nullable<short> ca, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToPOSCode", DbType="NVarChar(10)")] string toPOSCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemCode", DbType="NVarChar(20)")] string itemCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceCode", DbType="NVarChar(5)")] string serviceCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromPOSCode", DbType="NVarChar(10)")] string fromPOSCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MailTripNumber", DbType="Int")] System.Nullable<int> mailTripNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostBagNumber", DbType="Int")] System.Nullable<int> postBagNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostBagTypeCode", DbType="NVarChar(10)")] string postBagTypeCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IncomingDate", DbType="DateTime")] System.Nullable<System.DateTime> incomingDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Year", DbType="NVarChar(8)")] string year, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BatchCode", DbType="NVarChar(50)")] string batchCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AcceptancePOSCode", DbType="NVarChar(10)")] string acceptancePOSCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerCode", DbType="NVarChar(20)")] string customerCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SenderFullname", DbType="NVarChar(250)")] string senderFullname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SenderAddress", DbType="NVarChar(250)")] string senderAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SenderTel", DbType="NVarChar(50)")] string senderTel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SendingTime", DbType="DateTime")] System.Nullable<System.DateTime> sendingTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiverFullname", DbType="NVarChar(250)")] string receiverFullname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiverAddress", DbType="NVarChar(250)")] string receiverAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiverTel", DbType="NVarChar(50)")] string receiverTel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Weight", DbType="Float")] System.Nullable<double> weight, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WeightConvert", DbType="Float")] System.Nullable<double> weightConvert, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SendingContent", DbType="NVarChar(250)")] string sendingContent, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Value", DbType="Float")] System.Nullable<double> value, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LyDo", DbType="NVarChar(500)")] string lyDo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayHuy", DbType="DateTime")] System.Nullable<System.DateTime> ngayHuy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngay, ca, toPOSCode, itemCode, serviceCode, fromPOSCode, mailTripNumber, postBagNumber, postBagTypeCode, incomingDate, year, batchCode, acceptancePOSCode, customerCode, senderFullname, senderAddress, senderTel, sendingTime, receiverFullname, receiverAddress, receiverTel, weight, weightConvert, sendingContent, value, lyDo, ngayHuy);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_tblBuuCucHuy_DanhSachResult
	{
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<short> _Ca;
		
		private string _ToPOSCode;
		
		private string _ItemCode;
		
		private string _ServiceCode;
		
		private string _FromPOSCode;
		
		private System.Nullable<int> _MailTripNumber;
		
		private System.Nullable<int> _PostBagNumber;
		
		private string _PostBagTypeCode;
		
		private System.Nullable<System.DateTime> _IncomingDate;
		
		private string _Year;
		
		private string _BatchCode;
		
		private string _AcceptancePOSCode;
		
		private string _CustomerCode;
		
		private string _SenderFullname;
		
		private string _SenderAddress;
		
		private string _SenderTel;
		
		private System.Nullable<System.DateTime> _SendingTime;
		
		private string _ReceiverFullname;
		
		private string _ReceiverAddress;
		
		private string _ReceiverTel;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<double> _WeightConvert;
		
		private string _SendingContent;
		
		private System.Nullable<double> _Value;
		
		private System.Nullable<bool> _DaPhat;
		
		private System.Nullable<bool> _DaChuyenHoan;
		
		private System.Nullable<bool> _DaHuy;
		
		private string _LyDo;
		
		private System.Nullable<System.DateTime> _NgayHuy;
		
		private System.Nullable<System.DateTime> _NgayHeThong;
		
		public sp_tblBuuCucHuy_DanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca", DbType="SmallInt")]
		public System.Nullable<short> Ca
		{
			get
			{
				return this._Ca;
			}
			set
			{
				if ((this._Ca != value))
				{
					this._Ca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToPOSCode", DbType="NVarChar(10)")]
		public string ToPOSCode
		{
			get
			{
				return this._ToPOSCode;
			}
			set
			{
				if ((this._ToPOSCode != value))
				{
					this._ToPOSCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="NVarChar(20)")]
		public string ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this._ItemCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceCode", DbType="NVarChar(5)")]
		public string ServiceCode
		{
			get
			{
				return this._ServiceCode;
			}
			set
			{
				if ((this._ServiceCode != value))
				{
					this._ServiceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromPOSCode", DbType="NVarChar(10)")]
		public string FromPOSCode
		{
			get
			{
				return this._FromPOSCode;
			}
			set
			{
				if ((this._FromPOSCode != value))
				{
					this._FromPOSCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailTripNumber", DbType="Int")]
		public System.Nullable<int> MailTripNumber
		{
			get
			{
				return this._MailTripNumber;
			}
			set
			{
				if ((this._MailTripNumber != value))
				{
					this._MailTripNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostBagNumber", DbType="Int")]
		public System.Nullable<int> PostBagNumber
		{
			get
			{
				return this._PostBagNumber;
			}
			set
			{
				if ((this._PostBagNumber != value))
				{
					this._PostBagNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostBagTypeCode", DbType="NVarChar(10)")]
		public string PostBagTypeCode
		{
			get
			{
				return this._PostBagTypeCode;
			}
			set
			{
				if ((this._PostBagTypeCode != value))
				{
					this._PostBagTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncomingDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> IncomingDate
		{
			get
			{
				return this._IncomingDate;
			}
			set
			{
				if ((this._IncomingDate != value))
				{
					this._IncomingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(8)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchCode", DbType="NVarChar(50)")]
		public string BatchCode
		{
			get
			{
				return this._BatchCode;
			}
			set
			{
				if ((this._BatchCode != value))
				{
					this._BatchCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptancePOSCode", DbType="NVarChar(10)")]
		public string AcceptancePOSCode
		{
			get
			{
				return this._AcceptancePOSCode;
			}
			set
			{
				if ((this._AcceptancePOSCode != value))
				{
					this._AcceptancePOSCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerCode", DbType="NVarChar(20)")]
		public string CustomerCode
		{
			get
			{
				return this._CustomerCode;
			}
			set
			{
				if ((this._CustomerCode != value))
				{
					this._CustomerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderFullname", DbType="NVarChar(255)")]
		public string SenderFullname
		{
			get
			{
				return this._SenderFullname;
			}
			set
			{
				if ((this._SenderFullname != value))
				{
					this._SenderFullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderAddress", DbType="NVarChar(255)")]
		public string SenderAddress
		{
			get
			{
				return this._SenderAddress;
			}
			set
			{
				if ((this._SenderAddress != value))
				{
					this._SenderAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderTel", DbType="NVarChar(50)")]
		public string SenderTel
		{
			get
			{
				return this._SenderTel;
			}
			set
			{
				if ((this._SenderTel != value))
				{
					this._SenderTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendingTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> SendingTime
		{
			get
			{
				return this._SendingTime;
			}
			set
			{
				if ((this._SendingTime != value))
				{
					this._SendingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverFullname", DbType="NVarChar(255)")]
		public string ReceiverFullname
		{
			get
			{
				return this._ReceiverFullname;
			}
			set
			{
				if ((this._ReceiverFullname != value))
				{
					this._ReceiverFullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverAddress", DbType="NVarChar(255)")]
		public string ReceiverAddress
		{
			get
			{
				return this._ReceiverAddress;
			}
			set
			{
				if ((this._ReceiverAddress != value))
				{
					this._ReceiverAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverTel", DbType="NVarChar(50)")]
		public string ReceiverTel
		{
			get
			{
				return this._ReceiverTel;
			}
			set
			{
				if ((this._ReceiverTel != value))
				{
					this._ReceiverTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightConvert", DbType="Float")]
		public System.Nullable<double> WeightConvert
		{
			get
			{
				return this._WeightConvert;
			}
			set
			{
				if ((this._WeightConvert != value))
				{
					this._WeightConvert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendingContent", DbType="NVarChar(255)")]
		public string SendingContent
		{
			get
			{
				return this._SendingContent;
			}
			set
			{
				if ((this._SendingContent != value))
				{
					this._SendingContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Float")]
		public System.Nullable<double> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaPhat", DbType="Bit")]
		public System.Nullable<bool> DaPhat
		{
			get
			{
				return this._DaPhat;
			}
			set
			{
				if ((this._DaPhat != value))
				{
					this._DaPhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaChuyenHoan", DbType="Bit")]
		public System.Nullable<bool> DaChuyenHoan
		{
			get
			{
				return this._DaChuyenHoan;
			}
			set
			{
				if ((this._DaChuyenHoan != value))
				{
					this._DaChuyenHoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaHuy", DbType="Bit")]
		public System.Nullable<bool> DaHuy
		{
			get
			{
				return this._DaHuy;
			}
			set
			{
				if ((this._DaHuy != value))
				{
					this._DaHuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDo", DbType="NVarChar(500)")]
		public string LyDo
		{
			get
			{
				return this._LyDo;
			}
			set
			{
				if ((this._LyDo != value))
				{
					this._LyDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHuy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHuy
		{
			get
			{
				return this._NgayHuy;
			}
			set
			{
				if ((this._NgayHuy != value))
				{
					this._NgayHuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHeThong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHeThong
		{
			get
			{
				return this._NgayHeThong;
			}
			set
			{
				if ((this._NgayHeThong != value))
				{
					this._NgayHeThong = value;
				}
			}
		}
	}
	
	public partial class sp_tblBuuCucHuy_ThongTinResult
	{
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<short> _Ca;
		
		private string _ToPOSCode;
		
		private string _ItemCode;
		
		private string _ServiceCode;
		
		private string _FromPOSCode;
		
		private System.Nullable<int> _MailTripNumber;
		
		private System.Nullable<int> _PostBagNumber;
		
		private string _PostBagTypeCode;
		
		private System.Nullable<System.DateTime> _IncomingDate;
		
		private string _Year;
		
		private string _BatchCode;
		
		private string _AcceptancePOSCode;
		
		private string _CustomerCode;
		
		private string _SenderFullname;
		
		private string _SenderAddress;
		
		private string _SenderTel;
		
		private System.Nullable<System.DateTime> _SendingTime;
		
		private string _ReceiverFullname;
		
		private string _ReceiverAddress;
		
		private string _ReceiverTel;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<double> _WeightConvert;
		
		private string _SendingContent;
		
		private System.Nullable<double> _Value;
		
		private System.Nullable<bool> _DaPhat;
		
		private System.Nullable<bool> _DaChuyenHoan;
		
		private System.Nullable<bool> _DaHuy;
		
		private string _LyDo;
		
		private System.Nullable<System.DateTime> _NgayHuy;
		
		private System.Nullable<System.DateTime> _NgayHeThong;
		
		public sp_tblBuuCucHuy_ThongTinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca", DbType="SmallInt")]
		public System.Nullable<short> Ca
		{
			get
			{
				return this._Ca;
			}
			set
			{
				if ((this._Ca != value))
				{
					this._Ca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToPOSCode", DbType="NVarChar(10)")]
		public string ToPOSCode
		{
			get
			{
				return this._ToPOSCode;
			}
			set
			{
				if ((this._ToPOSCode != value))
				{
					this._ToPOSCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="NVarChar(20)")]
		public string ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this._ItemCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceCode", DbType="NVarChar(5)")]
		public string ServiceCode
		{
			get
			{
				return this._ServiceCode;
			}
			set
			{
				if ((this._ServiceCode != value))
				{
					this._ServiceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromPOSCode", DbType="NVarChar(10)")]
		public string FromPOSCode
		{
			get
			{
				return this._FromPOSCode;
			}
			set
			{
				if ((this._FromPOSCode != value))
				{
					this._FromPOSCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailTripNumber", DbType="Int")]
		public System.Nullable<int> MailTripNumber
		{
			get
			{
				return this._MailTripNumber;
			}
			set
			{
				if ((this._MailTripNumber != value))
				{
					this._MailTripNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostBagNumber", DbType="Int")]
		public System.Nullable<int> PostBagNumber
		{
			get
			{
				return this._PostBagNumber;
			}
			set
			{
				if ((this._PostBagNumber != value))
				{
					this._PostBagNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostBagTypeCode", DbType="NVarChar(10)")]
		public string PostBagTypeCode
		{
			get
			{
				return this._PostBagTypeCode;
			}
			set
			{
				if ((this._PostBagTypeCode != value))
				{
					this._PostBagTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncomingDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> IncomingDate
		{
			get
			{
				return this._IncomingDate;
			}
			set
			{
				if ((this._IncomingDate != value))
				{
					this._IncomingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(8)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchCode", DbType="NVarChar(50)")]
		public string BatchCode
		{
			get
			{
				return this._BatchCode;
			}
			set
			{
				if ((this._BatchCode != value))
				{
					this._BatchCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptancePOSCode", DbType="NVarChar(10)")]
		public string AcceptancePOSCode
		{
			get
			{
				return this._AcceptancePOSCode;
			}
			set
			{
				if ((this._AcceptancePOSCode != value))
				{
					this._AcceptancePOSCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerCode", DbType="NVarChar(20)")]
		public string CustomerCode
		{
			get
			{
				return this._CustomerCode;
			}
			set
			{
				if ((this._CustomerCode != value))
				{
					this._CustomerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderFullname", DbType="NVarChar(255)")]
		public string SenderFullname
		{
			get
			{
				return this._SenderFullname;
			}
			set
			{
				if ((this._SenderFullname != value))
				{
					this._SenderFullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderAddress", DbType="NVarChar(255)")]
		public string SenderAddress
		{
			get
			{
				return this._SenderAddress;
			}
			set
			{
				if ((this._SenderAddress != value))
				{
					this._SenderAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderTel", DbType="NVarChar(50)")]
		public string SenderTel
		{
			get
			{
				return this._SenderTel;
			}
			set
			{
				if ((this._SenderTel != value))
				{
					this._SenderTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendingTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> SendingTime
		{
			get
			{
				return this._SendingTime;
			}
			set
			{
				if ((this._SendingTime != value))
				{
					this._SendingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverFullname", DbType="NVarChar(255)")]
		public string ReceiverFullname
		{
			get
			{
				return this._ReceiverFullname;
			}
			set
			{
				if ((this._ReceiverFullname != value))
				{
					this._ReceiverFullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverAddress", DbType="NVarChar(255)")]
		public string ReceiverAddress
		{
			get
			{
				return this._ReceiverAddress;
			}
			set
			{
				if ((this._ReceiverAddress != value))
				{
					this._ReceiverAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverTel", DbType="NVarChar(50)")]
		public string ReceiverTel
		{
			get
			{
				return this._ReceiverTel;
			}
			set
			{
				if ((this._ReceiverTel != value))
				{
					this._ReceiverTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightConvert", DbType="Float")]
		public System.Nullable<double> WeightConvert
		{
			get
			{
				return this._WeightConvert;
			}
			set
			{
				if ((this._WeightConvert != value))
				{
					this._WeightConvert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendingContent", DbType="NVarChar(255)")]
		public string SendingContent
		{
			get
			{
				return this._SendingContent;
			}
			set
			{
				if ((this._SendingContent != value))
				{
					this._SendingContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Float")]
		public System.Nullable<double> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaPhat", DbType="Bit")]
		public System.Nullable<bool> DaPhat
		{
			get
			{
				return this._DaPhat;
			}
			set
			{
				if ((this._DaPhat != value))
				{
					this._DaPhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaChuyenHoan", DbType="Bit")]
		public System.Nullable<bool> DaChuyenHoan
		{
			get
			{
				return this._DaChuyenHoan;
			}
			set
			{
				if ((this._DaChuyenHoan != value))
				{
					this._DaChuyenHoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaHuy", DbType="Bit")]
		public System.Nullable<bool> DaHuy
		{
			get
			{
				return this._DaHuy;
			}
			set
			{
				if ((this._DaHuy != value))
				{
					this._DaHuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDo", DbType="NVarChar(500)")]
		public string LyDo
		{
			get
			{
				return this._LyDo;
			}
			set
			{
				if ((this._LyDo != value))
				{
					this._LyDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHuy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHuy
		{
			get
			{
				return this._NgayHuy;
			}
			set
			{
				if ((this._NgayHuy != value))
				{
					this._NgayHuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHeThong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHeThong
		{
			get
			{
				return this._NgayHeThong;
			}
			set
			{
				if ((this._NgayHeThong != value))
				{
					this._NgayHeThong = value;
				}
			}
		}
	}
	
	public partial class sp_tblBuuCucHuy_DanhSach_THopResult
	{
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<double> _KhoiLuong;
		
		private System.Nullable<double> _SoTien;
		
		public sp_tblBuuCucHuy_DanhSach_THopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoiLuong", DbType="Float")]
		public System.Nullable<double> KhoiLuong
		{
			get
			{
				return this._KhoiLuong;
			}
			set
			{
				if ((this._KhoiLuong != value))
				{
					this._KhoiLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Float")]
		public System.Nullable<double> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this._SoTien = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
