#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daoTienThuCOD.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TienCOD")]
	public partial class linqTrangThaiKeToanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqTrangThaiKeToanDataContext() : 
				base(global::daoTienThuCOD.Properties.Settings.Default.TienCODConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqTrangThaiKeToanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqTrangThaiKeToanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqTrangThaiKeToanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqTrangThaiKeToanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblTrangThaiKeToan_ChotMo")]
		public int sp_tblTrangThaiKeToan_ChotMo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay", DbType="Date")] System.Nullable<System.DateTime> ngay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChotSoLieu", DbType="Bit")] System.Nullable<bool> chotSoLieu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc, ngay, chotSoLieu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblTrangThaiKeToan_ThongTin")]
		public ISingleResult<sp_tblTrangThaiKeToan_ThongTinResult> sp_tblTrangThaiKeToan_ThongTin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay", DbType="Date")] System.Nullable<System.DateTime> ngay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc, ngay);
			return ((ISingleResult<sp_tblTrangThaiKeToan_ThongTinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblTrangThaiKeToan_LayNgayChot")]
		public ISingleResult<sp_tblTrangThaiKeToan_LayNgayChotResult> sp_tblTrangThaiKeToan_LayNgayChot([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc);
			return ((ISingleResult<sp_tblTrangThaiKeToan_LayNgayChotResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblTrangThaiKeToan_Them")]
		public int sp_tblTrangThaiKeToan_Them([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay", DbType="Date")] System.Nullable<System.DateTime> ngay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChiIP", DbType="NVarChar(50)")] string diaChiIP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenMay", DbType="NVarChar(150)")] string tenMay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAC", DbType="NVarChar(50)")] string mAC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc, ngay, diaChiIP, tenMay, mAC);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblTrangThaiKeToan_DanhSach")]
		public ISingleResult<sp_tblTrangThaiKeToan_DanhSachResult> sp_tblTrangThaiKeToan_DanhSach([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc);
			return ((ISingleResult<sp_tblTrangThaiKeToan_DanhSachResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_tblTrangThaiKeToan_ThongTinResult
	{
		
		private string _MaBuuCuc;
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<bool> _ChotSoLieu;
		
		private string _DiaChiIP;
		
		private string _TenMay;
		
		private string _MAC;
		
		private System.Nullable<System.DateTime> _NgayChot;
		
		private System.Nullable<System.DateTime> _NgayMo;
		
		private System.Nullable<System.DateTime> _NgayHeThong;
		
		public sp_tblTrangThaiKeToan_ThongTinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuuCuc", DbType="NVarChar(10)")]
		public string MaBuuCuc
		{
			get
			{
				return this._MaBuuCuc;
			}
			set
			{
				if ((this._MaBuuCuc != value))
				{
					this._MaBuuCuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChotSoLieu", DbType="Bit")]
		public System.Nullable<bool> ChotSoLieu
		{
			get
			{
				return this._ChotSoLieu;
			}
			set
			{
				if ((this._ChotSoLieu != value))
				{
					this._ChotSoLieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiIP", DbType="NVarChar(50)")]
		public string DiaChiIP
		{
			get
			{
				return this._DiaChiIP;
			}
			set
			{
				if ((this._DiaChiIP != value))
				{
					this._DiaChiIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMay", DbType="NVarChar(150)")]
		public string TenMay
		{
			get
			{
				return this._TenMay;
			}
			set
			{
				if ((this._TenMay != value))
				{
					this._TenMay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAC", DbType="NVarChar(50)")]
		public string MAC
		{
			get
			{
				return this._MAC;
			}
			set
			{
				if ((this._MAC != value))
				{
					this._MAC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChot", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChot
		{
			get
			{
				return this._NgayChot;
			}
			set
			{
				if ((this._NgayChot != value))
				{
					this._NgayChot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMo", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMo
		{
			get
			{
				return this._NgayMo;
			}
			set
			{
				if ((this._NgayMo != value))
				{
					this._NgayMo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHeThong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHeThong
		{
			get
			{
				return this._NgayHeThong;
			}
			set
			{
				if ((this._NgayHeThong != value))
				{
					this._NgayHeThong = value;
				}
			}
		}
	}
	
	public partial class sp_tblTrangThaiKeToan_LayNgayChotResult
	{
		
		private string _MaBuuCuc;
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<bool> _ChotSoLieu;
		
		private string _DiaChiIP;
		
		private string _TenMay;
		
		private string _MAC;
		
		private System.Nullable<System.DateTime> _NgayChot;
		
		private System.Nullable<System.DateTime> _NgayMo;
		
		private System.Nullable<System.DateTime> _NgayHeThong;
		
		public sp_tblTrangThaiKeToan_LayNgayChotResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuuCuc", DbType="NVarChar(10)")]
		public string MaBuuCuc
		{
			get
			{
				return this._MaBuuCuc;
			}
			set
			{
				if ((this._MaBuuCuc != value))
				{
					this._MaBuuCuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChotSoLieu", DbType="Bit")]
		public System.Nullable<bool> ChotSoLieu
		{
			get
			{
				return this._ChotSoLieu;
			}
			set
			{
				if ((this._ChotSoLieu != value))
				{
					this._ChotSoLieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiIP", DbType="NVarChar(50)")]
		public string DiaChiIP
		{
			get
			{
				return this._DiaChiIP;
			}
			set
			{
				if ((this._DiaChiIP != value))
				{
					this._DiaChiIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMay", DbType="NVarChar(150)")]
		public string TenMay
		{
			get
			{
				return this._TenMay;
			}
			set
			{
				if ((this._TenMay != value))
				{
					this._TenMay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAC", DbType="NVarChar(50)")]
		public string MAC
		{
			get
			{
				return this._MAC;
			}
			set
			{
				if ((this._MAC != value))
				{
					this._MAC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChot", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChot
		{
			get
			{
				return this._NgayChot;
			}
			set
			{
				if ((this._NgayChot != value))
				{
					this._NgayChot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMo", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMo
		{
			get
			{
				return this._NgayMo;
			}
			set
			{
				if ((this._NgayMo != value))
				{
					this._NgayMo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHeThong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHeThong
		{
			get
			{
				return this._NgayHeThong;
			}
			set
			{
				if ((this._NgayHeThong != value))
				{
					this._NgayHeThong = value;
				}
			}
		}
	}
	
	public partial class sp_tblTrangThaiKeToan_DanhSachResult
	{
		
		private string _MaBuuCuc;
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<bool> _ChotSoLieu;
		
		private string _DiaChiIP;
		
		private string _TenMay;
		
		private string _MAC;
		
		private System.Nullable<System.DateTime> _NgayChot;
		
		private System.Nullable<System.DateTime> _NgayMo;
		
		private System.Nullable<System.DateTime> _NgayHeThong;
		
		public sp_tblTrangThaiKeToan_DanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuuCuc", DbType="NVarChar(10)")]
		public string MaBuuCuc
		{
			get
			{
				return this._MaBuuCuc;
			}
			set
			{
				if ((this._MaBuuCuc != value))
				{
					this._MaBuuCuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChotSoLieu", DbType="Bit")]
		public System.Nullable<bool> ChotSoLieu
		{
			get
			{
				return this._ChotSoLieu;
			}
			set
			{
				if ((this._ChotSoLieu != value))
				{
					this._ChotSoLieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiIP", DbType="NVarChar(50)")]
		public string DiaChiIP
		{
			get
			{
				return this._DiaChiIP;
			}
			set
			{
				if ((this._DiaChiIP != value))
				{
					this._DiaChiIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMay", DbType="NVarChar(150)")]
		public string TenMay
		{
			get
			{
				return this._TenMay;
			}
			set
			{
				if ((this._TenMay != value))
				{
					this._TenMay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAC", DbType="NVarChar(50)")]
		public string MAC
		{
			get
			{
				return this._MAC;
			}
			set
			{
				if ((this._MAC != value))
				{
					this._MAC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChot", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChot
		{
			get
			{
				return this._NgayChot;
			}
			set
			{
				if ((this._NgayChot != value))
				{
					this._NgayChot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMo", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMo
		{
			get
			{
				return this._NgayMo;
			}
			set
			{
				if ((this._NgayMo != value))
				{
					this._NgayMo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHeThong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHeThong
		{
			get
			{
				return this._NgayHeThong;
			}
			set
			{
				if ((this._NgayHeThong != value))
				{
					this._NgayHeThong = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
