<?xml version="1.0" encoding="utf-8"?><Database Name="TienCOD" Class="linqTraTienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=TienCOD;Persist Security Info=True;User ID=sa" SettingsObjectName="daoTienThuCOD.Properties.Settings" SettingsPropertyName="TienCODConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblTraTien_CapNhatTrangThai" Method="sp_tblTraTien_CapNhatTrangThai">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Ngay" Parameter="ngay" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTraTien_DanhSach" Method="sp_tblTraTien_DanhSach">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_tblTraTien_DanhSachResult">
      <Column Name="MaBuuCuc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TranTime" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TranID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvokedFrom" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PAC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="AccountID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TranAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTraTien_LaySoLieu" Method="sp_tblTraTien_LaySoLieu">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Ngay" Parameter="ngay" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
</Database>