<?xml version="1.0" encoding="utf-8"?><Database Name="TienCOD" Class="linqKeToanBuuCucDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=TienCOD;Persist Security Info=True;User ID=sa" SettingsObjectName="daoTienThuCOD.Properties.Settings" SettingsPropertyName="TienCODConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblKeToan_DanhSach" Method="sp_tblKeToan_DanhSach">
    <ElementType Name="sp_tblKeToan_DanhSachResult">
      <Column Name="Ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaBuuCuc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MaBuuTa" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DuDauSanLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DuDauSoTien" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="NhanMoiSanLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NhanMoiSoTien" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="TraSanLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TraSoTien" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="ChuyenHoanSanLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChuyenHoanSoTien" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="PSGiamKhacSanLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSGiamKhacSoTien" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="DuCuoiSanLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DuCuoiSoTien" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKeToanBuuCuc_KetChuyen" Method="sp_tblKeToanBuuCuc_KetChuyen">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Ngay" Parameter="ngay" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKeToanBuuCuc_DanhSach_BuuCuc" Method="sp_tblKeToanBuuCuc_DanhSach_BuuCuc">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKeToanBuuCuc_DanhSach_DonVi" Method="sp_tblKeToanBuuCuc_DanhSach_DonVi">
    <Parameter Name="MaDonVi" Parameter="maDonVi" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKeToanBuuCuc_TyLe" Method="sp_tblKeToanBuuCuc_TyLe">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_tblKeToanBuuCuc_TyLeResult">
      <Column Name="Ma" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NhanMoiSoTien" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TraSoTien" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="ChuyenHoanSoTien" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="DuCuoiSoTien" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TyLePhat" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
      <Column Name="TyLeChuyenHoan" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
      <Column Name="TyLeTon" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKeToanBuuCuc_TyLe_DonVi" Method="sp_tblKeToanBuuCuc_TyLe_DonVi">
    <Parameter Name="MaDonVi" Parameter="maDonVi" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
</Database>