<?xml version="1.0" encoding="utf-8"?><Database Name="KeToanSoDu" Class="linqKeToanSoDuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=KeToanSoDu;Persist Security Info=True;User ID=sa" SettingsObjectName="daoKeToanSoDu.Properties.Settings" SettingsPropertyName="KeToanSoDuConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblKeToanSoDu_BaoCao_DonVi" Method="sp_tblKeToanSoDu_BaoCao_DonVi">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MaDonVi" Parameter="maDonVi" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="NhomDonVi" Parameter="nhomDonVi" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="sp_tblKeToanSoDu_BaoCao_DonViResult">
      <Column Name="DonVi" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="BuuCuc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TCBCTapTrung" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TCBCThanhToanTaiDonVi" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TKBD" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="KinhDoanh" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="Cong" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhTCBCTapTrung" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhTCBCThanhToanTaiDonVi" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhTKBD" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhKinhDoanh" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhCong" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKeToanSoDu_KhoiTao" Method="sp_tblKeToanSoDu_KhoiTao">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="MaDonVi" Parameter="maDonVi" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Thang" Parameter="thang" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKeToanSoDu_BaoCao_Ngay" Method="sp_tblKeToanSoDu_BaoCao_Ngay">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MaDonVi" Parameter="maDonVi" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_tblKeToanSoDu_BaoCao_NgayResult">
      <Column Name="Ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TCBCTapTrung" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TCBCThanhToanTaiDonVi" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TKBD" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="KinhDoanh" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="Cong" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhTCBCTapTrung" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhTCBCThanhToanTaiDonVi" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhTKBD" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhKinhDoanh" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="tgnhCong" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKeToanSoDu_DanhSachNhap" Method="sp_tblKeToanSoDu_DanhSachNhap">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_tblKeToanSoDu_DanhSachNhapResult">
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKeToanNgay" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaBuuCuc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DinhMucLuuQuyTCBC" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="DinhMucLuuQuyTKBD" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="DinhMucLuuQuyTCBC_DonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="DinhMucLuuQuyTKBD_DonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="TCBCTapTrung" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="TCBCThanhToanTaiDonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="TKBD" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="KinhDoanh" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="Cong" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="dkTCBCTapTrung" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="dkTCBCThanhToanTaiDonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="dkTKBD" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="dkKinhDoanh" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="dkCong" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Khoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKeToanSoDu_ThongTin_BuuCuc" Method="sp_tblKeToanSoDu_ThongTin_BuuCuc">
    <Parameter Name="MaBuuCuc" Parameter="maBuuCuc" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_tblKeToanSoDu_ThongTin_BuuCucResult">
      <Column Name="MaBuuCuc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BuuCuc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MaDonVi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MaKeToan" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DonVi" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="TenTat" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKeToanSoDu_BaoCao_SoDuCuoiNgay" Method="sp_tblKeToanSoDu_BaoCao_SoDuCuoiNgay">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MaDonVi" Parameter="maDonVi" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="NhomDonVi" Parameter="nhomDonVi" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="sp_tblKeToanSoDu_BaoCao_SoDuCuoiNgayResult">
      <Column Name="MaBuuCuc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DonVi" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="HinhThuc" Type="System.String" DbType="NVarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="DinhMucLuuQuyTCBC_DonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="DinhMucLuuQuyTKBD_DonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="TCBCTapTrung" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TCBCThanhToanTaiDonVi" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="TKBD" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="KinhDoanh" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="Cong" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKeToanSoDu_DanhSachTheoDonVi" Method="sp_tblKeToanSoDu_DanhSachTheoDonVi">
    <Parameter Name="MaDonVi" Parameter="maDonVi" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Ngay" Parameter="ngay" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_tblKeToanSoDu_DanhSachTheoDonViResult">
      <Column Name="STT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MaKeToanNgay" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaBuuCuc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DonVi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DinhMucLuuQuyTCBC" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="DinhMucLuuQuyTKBD" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="DinhMucLuuQuyTCBC_DonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="DinhMucLuuQuyTKBD_DonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="TCBCTapTrung" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="TCBCThanhToanTaiDonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="TKBD" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="KinhDoanh" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="Cong" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="dkTCBCTapTrung" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="dkTCBCThanhToanTaiDonVi" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="dkTKBD" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="dkKinhDoanh" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="dkCong" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Khoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChuaNhap" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>