#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daoKeToanSoDu.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KeToanSoDu")]
	public partial class linqKeToanSoDuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqKeToanSoDuDataContext() : 
				base(global::daoKeToanSoDu.Properties.Settings.Default.KeToanSoDuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqKeToanSoDuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqKeToanSoDuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqKeToanSoDuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqKeToanSoDuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblKeToanSoDu_BaoCao_DonVi")]
		public ISingleResult<sp_tblKeToanSoDu_BaoCao_DonViResult> sp_tblKeToanSoDu_BaoCao_DonVi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="Date")] System.Nullable<System.DateTime> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NhomDonVi", DbType="Bit")] System.Nullable<bool> nhomDonVi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tuNgay, denNgay, maDonVi, nhomDonVi);
			return ((ISingleResult<sp_tblKeToanSoDu_BaoCao_DonViResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblKeToanSoDu_KhoiTao")]
		public int sp_tblKeToanSoDu_KhoiTao([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thang", DbType="SmallInt")] System.Nullable<short> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc, maDonVi, thang, nam);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblKeToanSoDu_BaoCao_Ngay")]
		public ISingleResult<sp_tblKeToanSoDu_BaoCao_NgayResult> sp_tblKeToanSoDu_BaoCao_Ngay([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="Date")] System.Nullable<System.DateTime> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tuNgay, denNgay, maDonVi);
			return ((ISingleResult<sp_tblKeToanSoDu_BaoCao_NgayResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblKeToanSoDu_DanhSachNhap")]
		public ISingleResult<sp_tblKeToanSoDu_DanhSachNhapResult> sp_tblKeToanSoDu_DanhSachNhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="Date")] System.Nullable<System.DateTime> denNgay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc, tuNgay, denNgay);
			return ((ISingleResult<sp_tblKeToanSoDu_DanhSachNhapResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblKeToanSoDu_ThongTin_BuuCuc")]
		public ISingleResult<sp_tblKeToanSoDu_ThongTin_BuuCucResult> sp_tblKeToanSoDu_ThongTin_BuuCuc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBuuCuc", DbType="NVarChar(10)")] string maBuuCuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBuuCuc);
			return ((ISingleResult<sp_tblKeToanSoDu_ThongTin_BuuCucResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblKeToanSoDu_BaoCao_SoDuCuoiNgay")]
		public ISingleResult<sp_tblKeToanSoDu_BaoCao_SoDuCuoiNgayResult> sp_tblKeToanSoDu_BaoCao_SoDuCuoiNgay([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="Date")] System.Nullable<System.DateTime> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NhomDonVi", DbType="Bit")] System.Nullable<bool> nhomDonVi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tuNgay, denNgay, maDonVi, nhomDonVi);
			return ((ISingleResult<sp_tblKeToanSoDu_BaoCao_SoDuCuoiNgayResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblKeToanSoDu_DanhSachTheoDonVi")]
		public ISingleResult<sp_tblKeToanSoDu_DanhSachTheoDonViResult> sp_tblKeToanSoDu_DanhSachTheoDonVi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonVi", DbType="NVarChar(10)")] string maDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay", DbType="Date")] System.Nullable<System.DateTime> ngay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maDonVi, ngay);
			return ((ISingleResult<sp_tblKeToanSoDu_DanhSachTheoDonViResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_tblKeToanSoDu_BaoCao_DonViResult
	{
		
		private string _DonVi;
		
		private string _BuuCuc;
		
		private System.Nullable<decimal> _TCBCTapTrung;
		
		private System.Nullable<decimal> _TCBCThanhToanTaiDonVi;
		
		private System.Nullable<decimal> _TKBD;
		
		private System.Nullable<decimal> _KinhDoanh;
		
		private System.Nullable<decimal> _Cong;
		
		private System.Nullable<decimal> _tgnhTCBCTapTrung;
		
		private System.Nullable<decimal> _tgnhTCBCThanhToanTaiDonVi;
		
		private System.Nullable<decimal> _tgnhTKBD;
		
		private System.Nullable<decimal> _tgnhKinhDoanh;
		
		private System.Nullable<decimal> _tgnhCong;
		
		public sp_tblKeToanSoDu_BaoCao_DonViResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(80)")]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this._DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuuCuc", DbType="NVarChar(50)")]
		public string BuuCuc
		{
			get
			{
				return this._BuuCuc;
			}
			set
			{
				if ((this._BuuCuc != value))
				{
					this._BuuCuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCTapTrung", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TCBCTapTrung
		{
			get
			{
				return this._TCBCTapTrung;
			}
			set
			{
				if ((this._TCBCTapTrung != value))
				{
					this._TCBCTapTrung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCThanhToanTaiDonVi", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TCBCThanhToanTaiDonVi
		{
			get
			{
				return this._TCBCThanhToanTaiDonVi;
			}
			set
			{
				if ((this._TCBCThanhToanTaiDonVi != value))
				{
					this._TCBCThanhToanTaiDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TKBD", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TKBD
		{
			get
			{
				return this._TKBD;
			}
			set
			{
				if ((this._TKBD != value))
				{
					this._TKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhDoanh", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> KinhDoanh
		{
			get
			{
				return this._KinhDoanh;
			}
			set
			{
				if ((this._KinhDoanh != value))
				{
					this._KinhDoanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cong", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Cong
		{
			get
			{
				return this._Cong;
			}
			set
			{
				if ((this._Cong != value))
				{
					this._Cong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhTCBCTapTrung", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhTCBCTapTrung
		{
			get
			{
				return this._tgnhTCBCTapTrung;
			}
			set
			{
				if ((this._tgnhTCBCTapTrung != value))
				{
					this._tgnhTCBCTapTrung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhTCBCThanhToanTaiDonVi", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhTCBCThanhToanTaiDonVi
		{
			get
			{
				return this._tgnhTCBCThanhToanTaiDonVi;
			}
			set
			{
				if ((this._tgnhTCBCThanhToanTaiDonVi != value))
				{
					this._tgnhTCBCThanhToanTaiDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhTKBD", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhTKBD
		{
			get
			{
				return this._tgnhTKBD;
			}
			set
			{
				if ((this._tgnhTKBD != value))
				{
					this._tgnhTKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhKinhDoanh", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhKinhDoanh
		{
			get
			{
				return this._tgnhKinhDoanh;
			}
			set
			{
				if ((this._tgnhKinhDoanh != value))
				{
					this._tgnhKinhDoanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhCong", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhCong
		{
			get
			{
				return this._tgnhCong;
			}
			set
			{
				if ((this._tgnhCong != value))
				{
					this._tgnhCong = value;
				}
			}
		}
	}
	
	public partial class sp_tblKeToanSoDu_BaoCao_NgayResult
	{
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<decimal> _TCBCTapTrung;
		
		private System.Nullable<decimal> _TCBCThanhToanTaiDonVi;
		
		private System.Nullable<decimal> _TKBD;
		
		private System.Nullable<decimal> _KinhDoanh;
		
		private System.Nullable<decimal> _Cong;
		
		private System.Nullable<decimal> _tgnhTCBCTapTrung;
		
		private System.Nullable<decimal> _tgnhTCBCThanhToanTaiDonVi;
		
		private System.Nullable<decimal> _tgnhTKBD;
		
		private System.Nullable<decimal> _tgnhKinhDoanh;
		
		private System.Nullable<decimal> _tgnhCong;
		
		public sp_tblKeToanSoDu_BaoCao_NgayResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCTapTrung", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TCBCTapTrung
		{
			get
			{
				return this._TCBCTapTrung;
			}
			set
			{
				if ((this._TCBCTapTrung != value))
				{
					this._TCBCTapTrung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCThanhToanTaiDonVi", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TCBCThanhToanTaiDonVi
		{
			get
			{
				return this._TCBCThanhToanTaiDonVi;
			}
			set
			{
				if ((this._TCBCThanhToanTaiDonVi != value))
				{
					this._TCBCThanhToanTaiDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TKBD", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TKBD
		{
			get
			{
				return this._TKBD;
			}
			set
			{
				if ((this._TKBD != value))
				{
					this._TKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhDoanh", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> KinhDoanh
		{
			get
			{
				return this._KinhDoanh;
			}
			set
			{
				if ((this._KinhDoanh != value))
				{
					this._KinhDoanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cong", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Cong
		{
			get
			{
				return this._Cong;
			}
			set
			{
				if ((this._Cong != value))
				{
					this._Cong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhTCBCTapTrung", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhTCBCTapTrung
		{
			get
			{
				return this._tgnhTCBCTapTrung;
			}
			set
			{
				if ((this._tgnhTCBCTapTrung != value))
				{
					this._tgnhTCBCTapTrung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhTCBCThanhToanTaiDonVi", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhTCBCThanhToanTaiDonVi
		{
			get
			{
				return this._tgnhTCBCThanhToanTaiDonVi;
			}
			set
			{
				if ((this._tgnhTCBCThanhToanTaiDonVi != value))
				{
					this._tgnhTCBCThanhToanTaiDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhTKBD", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhTKBD
		{
			get
			{
				return this._tgnhTKBD;
			}
			set
			{
				if ((this._tgnhTKBD != value))
				{
					this._tgnhTKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhKinhDoanh", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhKinhDoanh
		{
			get
			{
				return this._tgnhKinhDoanh;
			}
			set
			{
				if ((this._tgnhKinhDoanh != value))
				{
					this._tgnhKinhDoanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgnhCong", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> tgnhCong
		{
			get
			{
				return this._tgnhCong;
			}
			set
			{
				if ((this._tgnhCong != value))
				{
					this._tgnhCong = value;
				}
			}
		}
	}
	
	public partial class sp_tblKeToanSoDu_DanhSachNhapResult
	{
		
		private System.Nullable<int> _STT;
		
		private string _MaKeToanNgay;
		
		private string _MaBuuCuc;
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTCBC;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTKBD;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTCBC_DonVi;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTKBD_DonVi;
		
		private System.Nullable<decimal> _TCBCTapTrung;
		
		private System.Nullable<decimal> _TCBCThanhToanTaiDonVi;
		
		private System.Nullable<decimal> _TKBD;
		
		private System.Nullable<decimal> _KinhDoanh;
		
		private System.Nullable<decimal> _Cong;
		
		private System.Nullable<decimal> _dkTCBCTapTrung;
		
		private System.Nullable<decimal> _dkTCBCThanhToanTaiDonVi;
		
		private System.Nullable<decimal> _dkTKBD;
		
		private System.Nullable<decimal> _dkKinhDoanh;
		
		private System.Nullable<decimal> _dkCong;
		
		private string _GhiChu;
		
		private bool _Khoa;
		
		public sp_tblKeToanSoDu_DanhSachNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKeToanNgay", DbType="NVarChar(20)")]
		public string MaKeToanNgay
		{
			get
			{
				return this._MaKeToanNgay;
			}
			set
			{
				if ((this._MaKeToanNgay != value))
				{
					this._MaKeToanNgay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuuCuc", DbType="NVarChar(10)")]
		public string MaBuuCuc
		{
			get
			{
				return this._MaBuuCuc;
			}
			set
			{
				if ((this._MaBuuCuc != value))
				{
					this._MaBuuCuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTCBC", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTCBC
		{
			get
			{
				return this._DinhMucLuuQuyTCBC;
			}
			set
			{
				if ((this._DinhMucLuuQuyTCBC != value))
				{
					this._DinhMucLuuQuyTCBC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTKBD", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTKBD
		{
			get
			{
				return this._DinhMucLuuQuyTKBD;
			}
			set
			{
				if ((this._DinhMucLuuQuyTKBD != value))
				{
					this._DinhMucLuuQuyTKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTCBC_DonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTCBC_DonVi
		{
			get
			{
				return this._DinhMucLuuQuyTCBC_DonVi;
			}
			set
			{
				if ((this._DinhMucLuuQuyTCBC_DonVi != value))
				{
					this._DinhMucLuuQuyTCBC_DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTKBD_DonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTKBD_DonVi
		{
			get
			{
				return this._DinhMucLuuQuyTKBD_DonVi;
			}
			set
			{
				if ((this._DinhMucLuuQuyTKBD_DonVi != value))
				{
					this._DinhMucLuuQuyTKBD_DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCTapTrung", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> TCBCTapTrung
		{
			get
			{
				return this._TCBCTapTrung;
			}
			set
			{
				if ((this._TCBCTapTrung != value))
				{
					this._TCBCTapTrung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCThanhToanTaiDonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> TCBCThanhToanTaiDonVi
		{
			get
			{
				return this._TCBCThanhToanTaiDonVi;
			}
			set
			{
				if ((this._TCBCThanhToanTaiDonVi != value))
				{
					this._TCBCThanhToanTaiDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TKBD", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> TKBD
		{
			get
			{
				return this._TKBD;
			}
			set
			{
				if ((this._TKBD != value))
				{
					this._TKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhDoanh", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> KinhDoanh
		{
			get
			{
				return this._KinhDoanh;
			}
			set
			{
				if ((this._KinhDoanh != value))
				{
					this._KinhDoanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cong", DbType="Decimal(25,0)")]
		public System.Nullable<decimal> Cong
		{
			get
			{
				return this._Cong;
			}
			set
			{
				if ((this._Cong != value))
				{
					this._Cong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkTCBCTapTrung", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> dkTCBCTapTrung
		{
			get
			{
				return this._dkTCBCTapTrung;
			}
			set
			{
				if ((this._dkTCBCTapTrung != value))
				{
					this._dkTCBCTapTrung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkTCBCThanhToanTaiDonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> dkTCBCThanhToanTaiDonVi
		{
			get
			{
				return this._dkTCBCThanhToanTaiDonVi;
			}
			set
			{
				if ((this._dkTCBCThanhToanTaiDonVi != value))
				{
					this._dkTCBCThanhToanTaiDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkTKBD", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> dkTKBD
		{
			get
			{
				return this._dkTKBD;
			}
			set
			{
				if ((this._dkTKBD != value))
				{
					this._dkTKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkKinhDoanh", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> dkKinhDoanh
		{
			get
			{
				return this._dkKinhDoanh;
			}
			set
			{
				if ((this._dkKinhDoanh != value))
				{
					this._dkKinhDoanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkCong", DbType="Decimal(25,0)")]
		public System.Nullable<decimal> dkCong
		{
			get
			{
				return this._dkCong;
			}
			set
			{
				if ((this._dkCong != value))
				{
					this._dkCong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(250)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="Bit NOT NULL")]
		public bool Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this._Khoa = value;
				}
			}
		}
	}
	
	public partial class sp_tblKeToanSoDu_ThongTin_BuuCucResult
	{
		
		private string _MaBuuCuc;
		
		private string _BuuCuc;
		
		private string _MaDonVi;
		
		private string _MaKeToan;
		
		private string _DonVi;
		
		private string _TenTat;
		
		public sp_tblKeToanSoDu_ThongTin_BuuCucResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuuCuc", DbType="NVarChar(255)")]
		public string MaBuuCuc
		{
			get
			{
				return this._MaBuuCuc;
			}
			set
			{
				if ((this._MaBuuCuc != value))
				{
					this._MaBuuCuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuuCuc", DbType="NVarChar(255)")]
		public string BuuCuc
		{
			get
			{
				return this._BuuCuc;
			}
			set
			{
				if ((this._BuuCuc != value))
				{
					this._BuuCuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="NVarChar(255)")]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					this._MaDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKeToan", DbType="NVarChar(10)")]
		public string MaKeToan
		{
			get
			{
				return this._MaKeToan;
			}
			set
			{
				if ((this._MaKeToan != value))
				{
					this._MaKeToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(80)")]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this._DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTat", DbType="NVarChar(20)")]
		public string TenTat
		{
			get
			{
				return this._TenTat;
			}
			set
			{
				if ((this._TenTat != value))
				{
					this._TenTat = value;
				}
			}
		}
	}
	
	public partial class sp_tblKeToanSoDu_BaoCao_SoDuCuoiNgayResult
	{
		
		private string _MaBuuCuc;
		
		private string _DonVi;
		
		private string _HinhThuc;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTCBC_DonVi;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTKBD_DonVi;
		
		private System.Nullable<decimal> _TCBCTapTrung;
		
		private System.Nullable<decimal> _TCBCThanhToanTaiDonVi;
		
		private System.Nullable<decimal> _TKBD;
		
		private System.Nullable<decimal> _KinhDoanh;
		
		private System.Nullable<decimal> _Cong;
		
		private System.Nullable<decimal> _STTsx;
		
		public sp_tblKeToanSoDu_BaoCao_SoDuCuoiNgayResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuuCuc", DbType="NVarChar(10)")]
		public string MaBuuCuc
		{
			get
			{
				return this._MaBuuCuc;
			}
			set
			{
				if ((this._MaBuuCuc != value))
				{
					this._MaBuuCuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(80)")]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this._DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThuc", DbType="NVarChar(18) NOT NULL", CanBeNull=false)]
		public string HinhThuc
		{
			get
			{
				return this._HinhThuc;
			}
			set
			{
				if ((this._HinhThuc != value))
				{
					this._HinhThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTCBC_DonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTCBC_DonVi
		{
			get
			{
				return this._DinhMucLuuQuyTCBC_DonVi;
			}
			set
			{
				if ((this._DinhMucLuuQuyTCBC_DonVi != value))
				{
					this._DinhMucLuuQuyTCBC_DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTKBD_DonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTKBD_DonVi
		{
			get
			{
				return this._DinhMucLuuQuyTKBD_DonVi;
			}
			set
			{
				if ((this._DinhMucLuuQuyTKBD_DonVi != value))
				{
					this._DinhMucLuuQuyTKBD_DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCTapTrung", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TCBCTapTrung
		{
			get
			{
				return this._TCBCTapTrung;
			}
			set
			{
				if ((this._TCBCTapTrung != value))
				{
					this._TCBCTapTrung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCThanhToanTaiDonVi", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TCBCThanhToanTaiDonVi
		{
			get
			{
				return this._TCBCThanhToanTaiDonVi;
			}
			set
			{
				if ((this._TCBCThanhToanTaiDonVi != value))
				{
					this._TCBCThanhToanTaiDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TKBD", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TKBD
		{
			get
			{
				return this._TKBD;
			}
			set
			{
				if ((this._TKBD != value))
				{
					this._TKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhDoanh", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> KinhDoanh
		{
			get
			{
				return this._KinhDoanh;
			}
			set
			{
				if ((this._KinhDoanh != value))
				{
					this._KinhDoanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cong", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Cong
		{
			get
			{
				return this._Cong;
			}
			set
			{
				if ((this._Cong != value))
				{
					this._Cong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTsx", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STTsx
		{
			get
			{
				return this._STTsx;
			}
			set
			{
				if ((this._STTsx != value))
				{
					this._STTsx = value;
				}
			}
		}
	}
	
	public partial class sp_tblKeToanSoDu_DanhSachTheoDonViResult
	{
		
		private System.Nullable<long> _STT;
		
		private string _MaKeToanNgay;
		
		private string _MaBuuCuc;
		
		private string _DonVi;
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTCBC;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTKBD;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTCBC_DonVi;
		
		private System.Nullable<decimal> _DinhMucLuuQuyTKBD_DonVi;
		
		private System.Nullable<decimal> _TCBCTapTrung;
		
		private System.Nullable<decimal> _TCBCThanhToanTaiDonVi;
		
		private System.Nullable<decimal> _TKBD;
		
		private System.Nullable<decimal> _KinhDoanh;
		
		private System.Nullable<decimal> _Cong;
		
		private System.Nullable<decimal> _dkTCBCTapTrung;
		
		private System.Nullable<decimal> _dkTCBCThanhToanTaiDonVi;
		
		private System.Nullable<decimal> _dkTKBD;
		
		private System.Nullable<decimal> _dkKinhDoanh;
		
		private System.Nullable<decimal> _dkCong;
		
		private string _GhiChu;
		
		private bool _Khoa;
		
		private System.Nullable<bool> _ChuaNhap;
		
		public sp_tblKeToanSoDu_DanhSachTheoDonViResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="BigInt")]
		public System.Nullable<long> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKeToanNgay", DbType="NVarChar(20)")]
		public string MaKeToanNgay
		{
			get
			{
				return this._MaKeToanNgay;
			}
			set
			{
				if ((this._MaKeToanNgay != value))
				{
					this._MaKeToanNgay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuuCuc", DbType="NVarChar(10)")]
		public string MaBuuCuc
		{
			get
			{
				return this._MaBuuCuc;
			}
			set
			{
				if ((this._MaBuuCuc != value))
				{
					this._MaBuuCuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(255)")]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this._DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTCBC", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTCBC
		{
			get
			{
				return this._DinhMucLuuQuyTCBC;
			}
			set
			{
				if ((this._DinhMucLuuQuyTCBC != value))
				{
					this._DinhMucLuuQuyTCBC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTKBD", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTKBD
		{
			get
			{
				return this._DinhMucLuuQuyTKBD;
			}
			set
			{
				if ((this._DinhMucLuuQuyTKBD != value))
				{
					this._DinhMucLuuQuyTKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTCBC_DonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTCBC_DonVi
		{
			get
			{
				return this._DinhMucLuuQuyTCBC_DonVi;
			}
			set
			{
				if ((this._DinhMucLuuQuyTCBC_DonVi != value))
				{
					this._DinhMucLuuQuyTCBC_DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMucLuuQuyTKBD_DonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> DinhMucLuuQuyTKBD_DonVi
		{
			get
			{
				return this._DinhMucLuuQuyTKBD_DonVi;
			}
			set
			{
				if ((this._DinhMucLuuQuyTKBD_DonVi != value))
				{
					this._DinhMucLuuQuyTKBD_DonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCTapTrung", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> TCBCTapTrung
		{
			get
			{
				return this._TCBCTapTrung;
			}
			set
			{
				if ((this._TCBCTapTrung != value))
				{
					this._TCBCTapTrung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCBCThanhToanTaiDonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> TCBCThanhToanTaiDonVi
		{
			get
			{
				return this._TCBCThanhToanTaiDonVi;
			}
			set
			{
				if ((this._TCBCThanhToanTaiDonVi != value))
				{
					this._TCBCThanhToanTaiDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TKBD", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> TKBD
		{
			get
			{
				return this._TKBD;
			}
			set
			{
				if ((this._TKBD != value))
				{
					this._TKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhDoanh", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> KinhDoanh
		{
			get
			{
				return this._KinhDoanh;
			}
			set
			{
				if ((this._KinhDoanh != value))
				{
					this._KinhDoanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cong", DbType="Decimal(25,0)")]
		public System.Nullable<decimal> Cong
		{
			get
			{
				return this._Cong;
			}
			set
			{
				if ((this._Cong != value))
				{
					this._Cong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkTCBCTapTrung", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> dkTCBCTapTrung
		{
			get
			{
				return this._dkTCBCTapTrung;
			}
			set
			{
				if ((this._dkTCBCTapTrung != value))
				{
					this._dkTCBCTapTrung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkTCBCThanhToanTaiDonVi", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> dkTCBCThanhToanTaiDonVi
		{
			get
			{
				return this._dkTCBCThanhToanTaiDonVi;
			}
			set
			{
				if ((this._dkTCBCThanhToanTaiDonVi != value))
				{
					this._dkTCBCThanhToanTaiDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkTKBD", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> dkTKBD
		{
			get
			{
				return this._dkTKBD;
			}
			set
			{
				if ((this._dkTKBD != value))
				{
					this._dkTKBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkKinhDoanh", DbType="Decimal(22,0)")]
		public System.Nullable<decimal> dkKinhDoanh
		{
			get
			{
				return this._dkKinhDoanh;
			}
			set
			{
				if ((this._dkKinhDoanh != value))
				{
					this._dkKinhDoanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkCong", DbType="Decimal(25,0)")]
		public System.Nullable<decimal> dkCong
		{
			get
			{
				return this._dkCong;
			}
			set
			{
				if ((this._dkCong != value))
				{
					this._dkCong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(250)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="Bit NOT NULL")]
		public bool Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this._Khoa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuaNhap", DbType="Bit")]
		public System.Nullable<bool> ChuaNhap
		{
			get
			{
				return this._ChuaNhap;
			}
			set
			{
				if ((this._ChuaNhap != value))
				{
					this._ChuaNhap = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
