#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daoSLBC.Database.DanhMuc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SoLieuBaoCao")]
	public partial class linqMauBieuBaoCaoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqMauBieuBaoCaoDataContext() : 
				base(global::daoSLBC.Properties.Settings.Default.SoLieuBaoCaoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqMauBieuBaoCaoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqMauBieuBaoCaoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqMauBieuBaoCaoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqMauBieuBaoCaoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblMauBieuBaoCaoDinhNghia_DanhSach")]
		public ISingleResult<sp_tblMauBieuBaoCaoDinhNghia_DanhSachResult> sp_tblMauBieuBaoCaoDinhNghia_DanhSach()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_tblMauBieuBaoCaoDinhNghia_DanhSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblMauBieuBaoCaoDinhNghia_ThongTin")]
		public ISingleResult<sp_tblMauBieuBaoCaoDinhNghia_ThongTinResult> sp_tblMauBieuBaoCaoDinhNghia_ThongTin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_tblMauBieuBaoCaoDinhNghia_ThongTinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblMauBieuBaoCaoDinhNghia_ThemSua")]
		public int sp_tblMauBieuBaoCaoDinhNghia_ThemSua([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ma", DbType="NVarChar(20)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ten", DbType="NVarChar(250)")] string ten, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTat", DbType="NVarChar(50)")] string tenTat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TieuDe1", DbType="NVarChar(250)")] string tieuDe1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TieuDe2", DbType="NVarChar(250)")] string tieuDe2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TieuDe3", DbType="NVarChar(250)")] string tieuDe3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Muc", DbType="Int")] System.Nullable<int> muc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cap", DbType="Int")] System.Nullable<int> cap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(500)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayApDung", DbType="Date")] System.Nullable<System.DateTime> ngayApDung, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayKetThuc", DbType="Date")] System.Nullable<System.DateTime> ngayKetThuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(50)")] string nguoiTao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nhom", DbType="Int")] System.Nullable<int> nhom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, ma, ten, tenTat, tieuDe1, tieuDe2, tieuDe3, muc, cap, ghiChu, ngayApDung, ngayKetThuc, nguoiTao, nhom);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_tblMauBieuBaoCaoDinhNghia_DanhSachResult
	{
		
		private int _ID;
		
		private string _Ma;
		
		private string _Ten;
		
		private string _TenTat;
		
		private string _TieuDe1;
		
		private string _TieuDe2;
		
		private string _TieuDe3;
		
		private System.Nullable<int> _Muc;
		
		private System.Nullable<int> _Cap;
		
		private string _GhiChu;
		
		private System.Nullable<System.DateTime> _NgayApDung;
		
		private System.Nullable<System.DateTime> _NgayKetThuc;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private System.Nullable<int> _Nhom;
		
		public sp_tblMauBieuBaoCaoDinhNghia_DanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="NVarChar(20)")]
		public string Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this._Ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(250)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this._Ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTat", DbType="NVarChar(50)")]
		public string TenTat
		{
			get
			{
				return this._TenTat;
			}
			set
			{
				if ((this._TenTat != value))
				{
					this._TenTat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe1", DbType="NVarChar(250)")]
		public string TieuDe1
		{
			get
			{
				return this._TieuDe1;
			}
			set
			{
				if ((this._TieuDe1 != value))
				{
					this._TieuDe1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe2", DbType="NVarChar(250)")]
		public string TieuDe2
		{
			get
			{
				return this._TieuDe2;
			}
			set
			{
				if ((this._TieuDe2 != value))
				{
					this._TieuDe2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe3", DbType="NVarChar(250)")]
		public string TieuDe3
		{
			get
			{
				return this._TieuDe3;
			}
			set
			{
				if ((this._TieuDe3 != value))
				{
					this._TieuDe3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muc", DbType="Int")]
		public System.Nullable<int> Muc
		{
			get
			{
				return this._Muc;
			}
			set
			{
				if ((this._Muc != value))
				{
					this._Muc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap", DbType="Int")]
		public System.Nullable<int> Cap
		{
			get
			{
				return this._Cap;
			}
			set
			{
				if ((this._Cap != value))
				{
					this._Cap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayApDung", DbType="Date")]
		public System.Nullable<System.DateTime> NgayApDung
		{
			get
			{
				return this._NgayApDung;
			}
			set
			{
				if ((this._NgayApDung != value))
				{
					this._NgayApDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this._NgayTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(50)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this._NguoiTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhom", DbType="Int")]
		public System.Nullable<int> Nhom
		{
			get
			{
				return this._Nhom;
			}
			set
			{
				if ((this._Nhom != value))
				{
					this._Nhom = value;
				}
			}
		}
	}
	
	public partial class sp_tblMauBieuBaoCaoDinhNghia_ThongTinResult
	{
		
		private int _ID;
		
		private string _Ma;
		
		private string _Ten;
		
		private string _TenTat;
		
		private string _TieuDe1;
		
		private string _TieuDe2;
		
		private string _TieuDe3;
		
		private System.Nullable<int> _Muc;
		
		private System.Nullable<int> _Cap;
		
		private string _GhiChu;
		
		private System.Nullable<System.DateTime> _NgayApDung;
		
		private System.Nullable<System.DateTime> _NgayKetThuc;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private System.Nullable<int> _Nhom;
		
		public sp_tblMauBieuBaoCaoDinhNghia_ThongTinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="NVarChar(20)")]
		public string Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this._Ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(250)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this._Ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTat", DbType="NVarChar(50)")]
		public string TenTat
		{
			get
			{
				return this._TenTat;
			}
			set
			{
				if ((this._TenTat != value))
				{
					this._TenTat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe1", DbType="NVarChar(250)")]
		public string TieuDe1
		{
			get
			{
				return this._TieuDe1;
			}
			set
			{
				if ((this._TieuDe1 != value))
				{
					this._TieuDe1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe2", DbType="NVarChar(250)")]
		public string TieuDe2
		{
			get
			{
				return this._TieuDe2;
			}
			set
			{
				if ((this._TieuDe2 != value))
				{
					this._TieuDe2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe3", DbType="NVarChar(250)")]
		public string TieuDe3
		{
			get
			{
				return this._TieuDe3;
			}
			set
			{
				if ((this._TieuDe3 != value))
				{
					this._TieuDe3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muc", DbType="Int")]
		public System.Nullable<int> Muc
		{
			get
			{
				return this._Muc;
			}
			set
			{
				if ((this._Muc != value))
				{
					this._Muc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap", DbType="Int")]
		public System.Nullable<int> Cap
		{
			get
			{
				return this._Cap;
			}
			set
			{
				if ((this._Cap != value))
				{
					this._Cap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayApDung", DbType="Date")]
		public System.Nullable<System.DateTime> NgayApDung
		{
			get
			{
				return this._NgayApDung;
			}
			set
			{
				if ((this._NgayApDung != value))
				{
					this._NgayApDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this._NgayTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(50)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this._NguoiTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhom", DbType="Int")]
		public System.Nullable<int> Nhom
		{
			get
			{
				return this._Nhom;
			}
			set
			{
				if ((this._Nhom != value))
				{
					this._Nhom = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
