<?xml version="1.0" encoding="utf-8"?><Database Name="SoLieuBaoCao" Class="linqMauBieuBaoCaoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=SoLieuBaoCao;Persist Security Info=True;User ID=sa" SettingsObjectName="daoSLBC.Properties.Settings" SettingsPropertyName="SoLieuBaoCaoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblMauBieuBaoCaoDinhNghia_DanhSach" Method="sp_tblMauBieuBaoCaoDinhNghia_DanhSach">
    <ElementType Name="sp_tblMauBieuBaoCaoDinhNghia_DanhSachResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TenTat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TieuDe1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TieuDe2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TieuDe3" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Muc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayApDung" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblMauBieuBaoCaoDinhNghia_ThongTin" Method="sp_tblMauBieuBaoCaoDinhNghia_ThongTin">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblMauBieuBaoCaoDinhNghia_ThongTinResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TenTat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TieuDe1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TieuDe2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TieuDe3" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Muc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayApDung" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblMauBieuBaoCaoDinhNghia_ThemSua" Method="sp_tblMauBieuBaoCaoDinhNghia_ThemSua">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ma" Parameter="ma" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Ten" Parameter="ten" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="TenTat" Parameter="tenTat" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TieuDe1" Parameter="tieuDe1" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="TieuDe2" Parameter="tieuDe2" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="TieuDe3" Parameter="tieuDe3" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Muc" Parameter="muc" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cap" Parameter="cap" Type="System.Int32" DbType="Int" />
    <Parameter Name="GhiChu" Parameter="ghiChu" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="NgayApDung" Parameter="ngayApDung" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NgayKetThuc" Parameter="ngayKetThuc" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NguoiTao" Parameter="nguoiTao" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Nhom" Parameter="nhom" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>