<?xml version="1.0" encoding="utf-8"?><Database Name="SoLieuBaoCao" Class="linqChiTieuMauBieuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.167;Initial Catalog=SoLieuBaoCao;Persist Security Info=True;User ID=sa" SettingsObjectName="daoSLBC.Properties.Settings" SettingsPropertyName="SoLieuBaoCaoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblChiTieuTheoMauBieu_ThongTin" Method="sp_tblChiTieuTheoMauBieu_ThongTin">
    <Parameter Name="IDMauBieu" Parameter="iDMauBieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDChiTieu" Parameter="iDChiTieu" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblChiTieuTheoMauBieu_ThongTinResult">
      <Column Name="IDMauBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDChiTieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThuTu" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="InDam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InNghieng" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="NhapTay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LayTuDong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblChiTieuTheoMauBieu_ThemSua" Method="sp_tblChiTieuTheoMauBieu_ThemSua">
    <Parameter Name="IDMauBieu" Parameter="iDMauBieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDChiTieu" Parameter="iDChiTieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="ThuTu" Parameter="thuTu" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="InDam" Parameter="inDam" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="InNghieng" Parameter="inNghieng" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="STTsx" Parameter="sTTsx" Type="System.Decimal" DbType="Decimal(18,3)" />
    <Parameter Name="NhapTay" Parameter="nhapTay" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LayTuDong" Parameter="layTuDong" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NguoiTao" Parameter="nguoiTao" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblChiTieuTheoMauBieu_DanhSach" Method="sp_tblChiTieuTheoMauBieu_DanhSach">
    <Parameter Name="IDMauBieu" Parameter="iDMauBieu" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblChiTieuTheoMauBieu_DanhSachResult">
      <Column Name="IDMauBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDChiTieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ma" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TenChiTieu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ThuTu" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="InDam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InNghieng" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="NhapTay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LayTuDong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblChiTieuTheoMauBieu_KhoiTao" Method="sp_tblChiTieuTheoMauBieu_KhoiTao">
    <Parameter Name="IDMauBieu" Parameter="iDMauBieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDChiTieu" Parameter="iDChiTieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="NguoiTao" Parameter="nguoiTao" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblChiTieuTheoMauBieu_Xoa" Method="sp_tblChiTieuTheoMauBieu_Xoa">
    <Parameter Name="IDMauBieu" Parameter="iDMauBieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDChiTieu" Parameter="iDChiTieu" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>